# Generated by Django 5.0 on 2023-12-12 08:43

import dcat.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="type",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="file",
            field=models.FileField(
                upload_to=dcat.models.Distribution._get_storage_path
            ),
        ),
        migrations.AlterField(
            model_name="licencedocument",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="mediatype",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="mediatype",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="mediatype",
            name="media_type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
