# Generated by Django 5.0 on 2023-12-16 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcat", "0003_checksum_distribution_checksum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="checksum",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dcat.checksum",
            ),
        ),
    ]
